import turtle
window = turtle.Screen()

stanley = turtle.Turtle()
stanley.speed(0)

stanley.color('red', 'yellow')
stanley.begin_fill()
while True:
    stanley.forward(200)
    stanley.left(170)
    if abs(stanley.pos()) < 1:
        break
stanley.end_fill()

stanley.penup()
stanley.goto(-150,0)
stanley.pendown()
stanley.forward(25)
stanley.right(90)
stanley.forward(25)
stanley.right(90)
stanley.forward(25)
stanley.right(90)
stanley.forward(25)

stanley.penup()
stanley.goto(0,-150)
stanley.pendown()
stanley.forward(30)
stanley.backward(15)
stanley.right(90)
stanley.forward(20)
stanley.left(90)
stanley.forward(15)
stanley.backward(30)

stanley.penup()
stanley.goto(30,-150)
stanley.pendown()
stanley.forward(30)
stanley.right(90)
stanley.forward(12)
stanley.backward(12)
stanley.left(90)
stanley.backward(15)
stanley.right(90)
stanley.forward(12)
stanley.backward(12)
stanley.left(90)
stanley.backward(15)
stanley.right(90)
stanley.forward(12)

stanley.penup()
stanley.goto(55,-150)
stanley.pendown()
stanley.left(90)
stanley.forward(30)
stanley.backward(30)
stanley.right(90)
stanley.forward(13)

stanley.penup()
stanley.goto(80,-150)
stanley.pendown()
stanley.left(90)
stanley.forward(30)
stanley.backward(30)
stanley.right(90)
stanley.forward(13)

stanley.penup()
stanley.goto(105,-150)
stanley.pendown()
stanley.left(90)
stanley.forward(30) 
stanley.right(90)
stanley.forward(13)
stanley.right(90)
stanley.forward(30)
stanley.right(90)
stanley.forward(13)


window.exitonclick()
